# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4d0cda36fb874c39c1e1bbdca7e61dafd8db8045c7640b2e235429d038dcc8a2963317e8100268540a603cdce0d56c3e0313a5ba16ea3b5137a5887f405c4ab

test:
  secret_key_base: 62b097792094d9cea70021c39680d439315dec01ead06df148e74b3934662af68e9063605f599756e6bb46e0f05c0a78286c38a920de0969bf54acedd644846d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
